blended_learning/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blended_learning.views.home', name='home'),
    # url(r'^blended_learning/', include('blended_learning.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('blended_learning.urls')),
    # url(r'', include('student.urls')),
    # url(r'', include('cards.url')),
    # url(r'', include('course_meta.urls')),
    url(r'^$', 'student.views.index'),
    url(r'', include('social_auth.urls')),
    url(r'^$','student.views.index'),
    url(r'^create_classroom$', 'student.views.create_classroom', name='create_classroom'),
    url(r'^delete_classroom$', 'student.views.delete_classroom', name='delete_classroom'),
    url(r'^logout_user$', 'student.views.logout_user', name='logout_user'),
    # oauth default urls
    url(r'^complete/(?P<backend>[^/]+)/$', 'social_auth.views.complete', name='socialauth_complete'),
    url(r'^associate/(?P<backend>[^/]+)/$', 'social_auth.views.auth', name='socialauth_associate_begin'),
    url(r'^associate/complete/(?P<backend>[^/]+)/$', 'social_auth.views.complete', name='socialauth_associate_complete'),
    url(r'^disconnect/(?P<backend>[^/]+)/$', 'social_auth.views.disconnect', name='socialauth_disconnect'),
    url(r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>[^/]+)/$', 'social_auth.views.disconnect', name='socialauth_disconnect_individual'),

    # our oauth urls
    url(r'^login/(?P<backend>[^/]+)/$', 'social_oauth.views.oauth_login', name='oauth_login'),
    url(r'^register/(?P<backend>[^/]+)/$', 'social_oauth.views.oauth_register', name='oauth_register'),
    url(r'^bind/(?P<backend>[^/]+)/$', 'social_oauth.views.oauth_bind', name='oauth_bind'),
    url(r'^oauth/newassociation$', 'social_oauth.views.new_association', name='new_association'),
    url(r'^oauth/authentication/success$', 'social_oauth.views.authentication_success', name='authentication_success'),
)
if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$','server'),
        )

django-social-auth/example/example/urls.py
from django.conf.urls.defaults import patterns, url, include
from django.contrib import admin

from app.views import home, done, logout, error, form, form2, close_login_popup
from app.facebook import facebook_view
from app.vkontakte import vkontakte_view
from app.odnoklassniki import ok_app, ok_app_info

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', home, name='home'),
    url(r'^done/$', done, name='done'),
    url(r'^error/$', error, name='error'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^form/$', form, name='form'),
    url(r'^form2/$', form2, name='form2'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^fb/', facebook_view, name='fb_app'),
    url(r'^vk/', vkontakte_view, name='vk_app'),
    url(r'^ok/$', ok_app, name='ok_app'),
    url(r'^ok/info/$', ok_app_info, name='ok_app_info'),
    url(r'^close_login_popup/$', close_login_popup, name='login_popup_close'),
    url(r'', include('social_auth.urls')),
)

python-social-auth/examples/django_example/example/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'example.app.views.home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^signup-email/', 'example.app.views.signup_email'),
    url(r'^email-sent/', 'example.app.views.validation_sent'),
    url(r'^login/$', 'example.app.views.home'),
    url(r'^logout/$', 'example.app.views.logout'),
    url(r'^done/$', 'example.app.views.done', name='done'),
    url(r'^ajax-auth/(?P<backend>[^/]+)/$', 'example.app.views.ajax_auth',
        name='ajax-auth'),
    url(r'^email/$', 'example.app.views.require_email', name='require_email'),
    url(r'', include('social.apps.django_app.urls', namespace='social'))
)

python-social-auth/social/apps/django_app/urls.py
"""URLs module"""
try:
    from django.conf.urls import patterns, url
except ImportError:
    # Django < 1.4
    from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('social.apps.django_app.views',
    # authentication / association
    url(r'^login/(?P<backend>[^/]+)/$', 'auth',
        name='begin'),
    url(r'^complete/(?P<backend>[^/]+)/$', 'complete',
        name='complete'),
    # disconnection
    url(r'^disconnect/(?P<backend>[^/]+)/$', 'disconnect',
        name='disconnect'),
    url(r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>[^/]+)/$',
        'disconnect', name='disconnect_individual'),
)

student/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blended_learning.views.home', name='home'),
    # url(r'^blended_learning/', include('blended_learning.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^create_classroom', 'student.views.create_classroom'),
    # url(r'^delete_classroom', 'student.views.delete_classroom'),
)

django-social-auth/example/app/models.py
# Define a custom User class to work with django-social-auth
from django.db import models


class CustomUserManager(models.Manager):
    def create_user(self, username, email):
        return self.model._default_manager.create(username=username)


class CustomUser(models.Model):
    username = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    def is_authenticated(self):
        return True

python-social-auth/examples/django_example/example/app/models.py
# Define a custom User class to work with django-social-auth
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

python-social-auth/examples/django_me_example/example/app/models.py
from mongoengine.fields import ListField
from mongoengine.django.auth import User


class User(User):
    """Extend Mongo Engine User model"""
    foo = ListField(default=[])

python-social-auth/examples/flask_example/models/user.py
from flask.ext.login import UserMixin

from flask_example import db


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(200))
    password = db.Column(db.String(200), default='')
    name = db.Column(db.String(100))
    email = db.Column(db.String(200))
    active = db.Column(db.Boolean, default=True)

    def is_active(self):
        return self.active

python-social-auth/examples/flask_me_example/models/user.py
from mongoengine import StringField, EmailField, BooleanField

from flask.ext.login import UserMixin

from flask_me_example import db


class User(db.Document, UserMixin):
    username = StringField(max_length=200)
    password = StringField(max_length=200, default='')
    name = StringField(max_length=100)
    email = EmailField()
    active = BooleanField(default=True)

    def is_active(self):
        return self.active

python-social-auth/examples/pyramid_example/example/models.py
from sqlalchemy import Column, Integer, String, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import scoped_session, sessionmaker

from zope.sqlalchemy import ZopeTransactionExtension


DBSession = scoped_session(sessionmaker(extension=ZopeTransactionExtension()))
Base = declarative_base()


class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    username = Column(String(200))
    email = Column(String(200))
    password = Column(String(200), default='')
    name = Column(String(100))
    email = Column(String(200))
    active = Column(Boolean, default=True)

python-social-auth/examples/tornado_example/models.py
from sqlalchemy import Column, Integer, String

from app import Base, engine


class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    username = Column(String(30), nullable=False)
    first_name = Column(String(30), nullable=True)
    last_name = Column(String(30), nullable=True)
    email = Column(String(75), nullable=False)
    password = Column(String(128), nullable=True)


if __name__ == '__main__':
    Base.metadata.create_all(engine)

python-social-auth/examples/webpy_example/models.py
from sqlalchemy import Column, Integer, String, Boolean
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()


class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    username = Column(String(200))
    password = Column(String(200), default='')
    name = Column(String(100))
    email = Column(String(200))
    active = Column(Boolean, default=True)

    def is_active(self):
        return self.active

    def is_authenticated(self):
        return True

django-social-auth/example/app/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from django.contrib.messages.api import get_messages

from social_auth import __version__ as version


def home(request):
    """Home view, displays login mechanism"""
    if request.user.is_authenticated():
        return HttpResponseRedirect('done')
    else:
        return render_to_response('home.html', {'version': version},
                                  RequestContext(request))


@login_required
def done(request):
    """Login complete view, displays user data"""
    ctx = {
        'version': version,
        'last_login': request.session.get('social_auth_last_login_backend')
    }
    return render_to_response('done.html', ctx, RequestContext(request))


def error(request):
    """Error view"""
    messages = get_messages(request)
    return render_to_response('error.html', {'version': version,
                                             'messages': messages},
                              RequestContext(request))


def logout(request):
    """Logs out user"""
    auth_logout(request)
    return HttpResponseRedirect('/')


def form(request):
    if request.method == 'POST' and request.POST.get('username'):
        request.session['saved_username'] = request.POST['username']
        backend = request.session['partial_pipeline']['backend']
        return redirect('socialauth_complete', backend=backend)
    return render_to_response('form.html', {}, RequestContext(request))


def form2(request):
    if request.method == 'POST' and request.POST.get('first_name'):
        request.session['saved_first_name'] = request.POST['first_name']
        backend = request.session['partial_pipeline']['backend']
        return redirect('socialauth_complete', backend=backend)
    return render_to_response('form2.html', {}, RequestContext(request))


def close_login_popup(request):
    return render_to_response('close_popup.html', {}, RequestContext(request))

python-social-auth/examples/django_example/example/app/views.py
import json

from django.conf import settings
from django.http import HttpResponse, HttpResponseBadRequest
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout, login

from social.backends.oauth import BaseOAuth1, BaseOAuth2
from social.backends.google import GooglePlusAuth
from social.apps.django_app.utils import strategy


def logout(request):
    """Logs out user"""
    auth_logout(request)
    return render_to_response('home.html', {}, RequestContext(request))


def home(request):
    """Home view, displays login mechanism"""
    if request.user.is_authenticated():
        return redirect('done')
    return render_to_response('home.html', {
        'plus_id': getattr(settings, 'SOCIAL_AUTH_GOOGLE_PLUS_KEY', None)
    }, RequestContext(request))


@login_required
def done(request):
    """Login complete view, displays user data"""
    scope = ' '.join(GooglePlusAuth.DEFAULT_SCOPE)
    return render_to_response('done.html', {
        'user': request.user,
        'plus_id': getattr(settings, 'SOCIAL_AUTH_GOOGLE_PLUS_KEY', None),
        'plus_scope': scope
    }, RequestContext(request))


def signup_email(request):
    return render_to_response('email_signup.html', {}, RequestContext(request))


def validation_sent(request):
    return render_to_response('validation_sent.html', {
        'email': request.session.get('email_validation_address')
    }, RequestContext(request))


def require_email(request):
    if request.method == 'POST':
        request.session['saved_email'] = request.POST.get('email')
        backend = request.session['partial_pipeline']['backend']
        return redirect('social:complete', backend=backend)
    return render_to_response('email.html', RequestContext(request))


@strategy('social:complete')
def ajax_auth(request, backend):
    backend = request.strategy.backend
    if isinstance(backend, BaseOAuth1):
        token = {
            'oauth_token': request.REQUEST.get('access_token'),
            'oauth_token_secret': request.REQUEST.get('access_token_secret'),
        }
    elif isinstance(backend, BaseOAuth2):
        token = request.REQUEST.get('access_token')
    else:
        raise HttpResponseBadRequest('Wrong backend type')
    user = request.strategy.backend.do_auth(token, ajax=True)
    login(request, user)
    data = {'id': user.id, 'username': user.username}
    return HttpResponse(json.dumps(data), mimetype='application/json')

python-social-auth/examples/django_me_example/example/app/views.py
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect


def home(request):
    """Home view, displays login mechanism"""
    if request.user.is_authenticated():
        return redirect('done')
    return render_to_response('home.html', {}, RequestContext(request))


@login_required
def done(request):
    """Login complete view, displays user data"""
    return render_to_response('done.html', {'user': request.user},
                              RequestContext(request))


def signup_email(request):
    return render_to_response('email_signup.html', {}, RequestContext(request))


def validation_sent(request):
    return render_to_response('validation_sent.html', {
        'email': request.session.get('email_validation_address')
    }, RequestContext(request))


def require_email(request):
    if request.method == 'POST':
        request.session['saved_email'] = request.POST.get('email')
        backend = request.session['partial_pipeline']['backend']
        return redirect('social:complete', backend=backend)
    return render_to_response('email.html', RequestContext(request))

python-social-auth/examples/pyramid_example/example/views.py
from pyramid.view import view_config


@view_config(route_name='home', renderer='templates/home.pt')
def home(request):
    return {}


@view_config(route_name='done', renderer='templates/done.pt')
def done(request):
    return {}

python-social-auth/examples/django_me_example/example/templates/base.html
<!doctype html>
<html>
  <head>
    <title>Social</title>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" rel="stylesheet" media="screen">
  </head>
  <body>
    {% block content %}{% endblock %}
    {% block scripts %}{% endblock %}

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/js/bootstrap.min.js" type="text/javascript"></script>
  </body>
</html>

python-social-auth/examples/django_me_example/example/templates/done.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<p>You are logged in as {{ user.username }}!</p>

<p>Associated:</p>
{% for assoc in backends.associated %}
  <div>
    <strong>{{ assoc.provider }}</strong>
    <form action="{% url 'social:disconnect_individual' assoc.provider assoc.id %}" method="post">{% csrf_token %}
      <button>Disconnect</button>
    </form>
  </div>
{% endfor %}

<p>Associate:</p>
<ul>
  {% for name in backends.not_associated %}
    <li>
      <a href="{% url 'social:begin' name %}">{{ name }}</a>
    </li>
  {% endfor %}
</ul>
{% endblock %}

python-social-auth/examples/django_me_example/example/templates/email.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <label for="email">Email address:</label>
  <input id="email" type="email" name="email" value="" />
  <button>Save</button>
</form>
{% endblock %}

python-social-auth/examples/django_me_example/example/templates/email_signup.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<form action="{% url 'social:complete' "email" %}" method="post">
  {% csrf_token %}
  <label for="email">Email address:</label>
  <input id="email" type="email" name="email" value="" />

  <label for="password">Password:</label>
  <input id="password" type="password" name="password" value="" />

  <label for="fullname">Full name:</label>
  <input id="fullname" type="text" name="fullname" value="" />

  <br />
  <button>Signup</button>
</form>
{% endblock %}

python-social-auth/examples/django_me_example/example/templates/home.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<a href="{% url 'social:begin' "google-oauth2" %}">Google OAuth2</a> <br />
<a href="{% url 'social:begin' "google-oauth" %}">Google OAuth</a> <br />
<a href="{% url 'social:begin' "google" %}">Google OpenId</a> <br />
<a href="{% url 'social:begin' "twitter" %}">Twitter OAuth</a> <br />
<a href="{% url 'social:begin' "yahoo" %}">Yahoo OpenId</a> <br />
<a href="{% url 'social:begin' "yahoo-oauth" %}">Yahoo OAuth</a> <br />
<a href="{% url 'social:begin' "stripe" %}">Stripe OAuth2</a> <br />
<a href="{% url 'social:begin' "strava" %}">Strava OAuth2</a> <br />
<a href="{% url 'social:begin' "facebook" %}">Facebook OAuth2</a> <br />
<a href="{% url 'social:begin' "facebook-app" %}">Facebook App</a> <br />
<a href="{% url 'social:begin' "angel" %}">Angel OAuth2</a> <br />
<a href="{% url 'social:begin' "behance" %}">Behance OAuth2</a> <br />
<a href="{% url 'social:begin' "bitbucket" %}">Bitbucket OAuth</a> <br />
<a href="{% url 'social:begin' "box" %}">Box.net OAuth2</a> <br />
<a href="{% url 'social:begin' "linkedin" %}">LinkedIn OAuth</a> <br />
<a href="{% url 'social:begin' "github" %}">Github OAuth2</a> <br />
<a href="{% url 'social:begin' "foursquare" %}">Foursquare OAuth2</a> <br />
<a href="{% url 'social:begin' "instagram" %}">Instagram OAuth2</a> <br />
<a href="{% url 'social:begin' "live" %}">Live OAuth2</a> <br />
<a href="{% url 'social:begin' "vk-oauth2" %}">VK.com OAuth2</a> <br />
<a href="{% url 'social:begin' "dailymotion" %}">Dailymotion OAuth2</a> <br />
<a href="{% url 'social:begin' "disqus" %}">Disqus OAuth2</a> <br />
<a href="{% url 'social:begin' "dropbox" %}">Dropbox OAuth</a> <br />
<a href="{% url 'social:begin' "evernote-sandbox" %}">Evernote OAuth (sandbox mode)</a> <br />
<a href="{% url 'social:begin' "fitbit" %}">Fitbit OAuth</a> <br />
<a href="{% url 'social:begin' "flickr" %}">Flickr OAuth</a> <br />
<a href="{% url 'social:begin' "soundcloud" %}">Soundcloud OAuth2</a> <br />
<a href="{% url 'social:begin' "thisismyjam" %}">ThisIsMyJam OAuth1</a> <br />
<a href="{% url 'social:begin' "stocktwits" %}">Stocktwits OAuth2</a> <br />
<a href="{% url 'social:begin' "tripit" %}">Tripit OAuth</a> <br />
<a href="{% url 'social:begin' "clef" %}">Clef OAuth</a> <br />
<a href="{% url 'social:begin' "twilio" %}">Twilio</a> <br />
<a href="{% url 'social:begin' "xing" %}">Xing OAuth</a> <br />
<a href="{% url 'social:begin' "yandex-oauth2" %}">Yandex OAuth2</a> <br />
<a href="{% url 'social:begin' "douban-oauth2" %}">Douban OAuth2</a> <br />
<a href="{% url 'social:begin' "mixcloud" %}">Mixcloud OAuth2</a> <br />
<a href="{% url 'social:begin' "rdio-oauth2" %}">Rdio OAuth2</a> <br />
<a href="{% url 'social:begin' "rdio-oauth1" %}">Rdio OAuth1</a> <br />
<a href="{% url 'social:begin' "yammer" %}">Yammer OAuth2</a> <br />
<a href="{% url 'social:begin' "stackoverflow" %}">Stackoverflow OAuth2</a> <br />
<a href="{% url 'social:begin' "readability" %}">Readability OAuth1</a> <br />
<a href="{% url 'social:begin' "skyrock" %}">Skyrock OAuth1</a> <br />
<a href="{% url 'social:begin' "tumblr" %}">Tumblr OAuth1</a> <br />
<a href="{% url 'social:begin' "reddit" %}">Reddit OAuth2</a> <br />
<a href="{% url 'social:begin' "podio" %}">Podio OAuth2</a> <br />
<a href="{% url 'social:begin' "amazon" %}">Amazon OAuth2</a> <br />
<a href="{% url 'social:begin' "steam" %}">Steam OpenId</a> <br />
<a href="{% url 'social:begin' "email" %}">Email Auth</a> <br />
<a href="{% url 'social:begin' "username" %}">Username Auth</a> <br />

<form action="{% url 'social:begin' "openid" %}" method="post">{% csrf_token %}
  <div>
    <label for="openid_identifier">OpenId provider</label>
    <input id="openid_identifier" type="text" value="" name="openid_identifier" />
    <input type="submit" value="Login" />
  </div>
</form>

<form action="{% url 'social:begin' "livejournal" %}" method="post">{% csrf_token %}
  <div>
    <label for="openid_lj_identifier">LiveJournal ID</label>
    <input id="openid_lj_identifier" type="text" value="" name="openid_lj_user" />
    <input type="submit" value="Login" />
  </div>
</form>

<form method="post" action="{% url 'social:complete' "persona" %}">
  <input type="hidden" name="assertion" value="" />
  <a rel="nofollow" id="persona" href="#">Persona</a>
</form>
{% endblock %}

{% block scripts %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
<script src="https://login.persona.org/include.js" type="text/javascript"></script>
<script type="text/javascript">
$(function () {
    $('#persona').on('click', function (e) {
        e.preventDefault();
        var self = $(this);

        navigator.id.get(function (assertion) {
            if (assertion) {
                self.parent('form')
                        .find('input[type=hidden]')
                        .attr('value', assertion)
                        .end()
                    .submit();
            } else {
                alert('Some error occurred');
            }
        });
    });
});
</script>
{% endblock %}

python-social-auth/examples/django_me_example/example/templates/username_signup.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<form action="{% url 'social:complete' "username" %}" method="post">
  {% csrf_token %}
  <label for="username">Username:</label>
  <input id="username" type="text" name="username" value="" />

  <label for="password">Password:</label>
  <input id="password" type="password" name="password" value="" />

  <label for="fullname">Full name:</label>
  <input id="fullname" type="text" name="fullname" value="" />

  <br />
  <button>Signup</button>
</form>
{% endblock %}

python-social-auth/examples/django_me_example/example/templates/validation_sent.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
A email validation was sent to {{ email }}.
{% endblock %}